### ISSUE TITLE
Exception "Something went wrong"

### ISSUE THREAD

**Issue by AqlaSolutions** [Robmaister/SharpNav#49]
<img src="http://content.screencast.com/users/wvlad/folders/Jing/media/ceeb2ce4-3d53-4a03-8791-d2f4262a5eab/2016-01-07_1610.png">

I sent the obj file by mail.

**Comment by Robmaister** [comment]
So looking into it, you're running into the limit of `while (++iter < 400000)` in CompactHeightfield.cs line 1556.

I think the problem here is that your generation settings are a bit inconsistent and build some massive contours that take more than 40000 (such as most of the playable parts of the map being a single contour). Primarily, your "Max Climb" appears to be 20x the agent height. If you drop this down to something more reasonable like 0.2-0.3, you should be able to avoid this issue.

Additionally, I was able to generate a mesh with the same connectivity with a cell size of 0.2 and a cell height of 0.25 in about 1/3 of the time it took for your original settings.

I'll probably go ahead and clean up the error message a bit but still have it fail unless there's a better solution or a really good reason to bump up the max iteration count (which is the same as Recast)

**Comment by AqlaSolutions** [comment]
Ok, now I understand what's going on. Thanks!

About cell size.. our designer asked me several times to set the cell size to the minimum (0.1) because of "bad generation" so 0.16 is already a compromise. ))

**Comment by Robmaister** [comment]
The problem with that is that as you shrink your cell size and height, you are exponentially increasing generation time and memory usage. Make sure all of the Agent settings actually match your character settings (in newer versions of the Examples program, Erode Radius is renamed to Agent Radius) and use the largest cell size/height you can get away with.

With a little experimentation from your map, I'd say you can probably get away with 0.25 size/0.2 height.

If there is any bad generation, send it my way and I should be able to find the bug pretty quickly.

**Comment by AqlaSolutions** [comment]
Ok, thank you again! I'm using the new version of Examples program, this is just our fork where we like that naming.

**Comment by Robmaister** [comment]
Did you guys find any good reason for increasing the limit of WalkContour? Or is the generation settings solution good enough for you? Feel free to close the issue if it is.

**Comment by AqlaSolutions** [comment]
Yes, that solution seems to be ok. Thank you for the explanation!
