### ISSUE TITLE
Using SharpNav.SharpDX in conjunction with SharpDX 3.0.1

### ISSUE THREAD

**Issue by Warpten** [Robmaister/SharpNav#59]
With the newest version of `SharpDX` that came out in December 2015, we are now unable to use some functions of the current NuGet (0.9.2) version of `SharpNav.SharpDX` without downgrading `SharpDX`.

The reason behind that is that `Vector3` and many different types are now in a different assembly, namely `SharpDX.Mathematics`.

This causes, for example, `TriangleEnumerable.FromVector3`, to not compile due to it referencing types that are in another assembly than the one it is looking in.

Obviously downgrading isn't that much of a problem but it would be greatly appreciated if this was fixed.

Thanks for looking into this!

![](http://i.imgur.com/asuKhKC.png)

Note: Using 1.0.0-alpha2 does not help.

**Comment by Robmaister** [comment]
I can take a look at this and fix the dependencies at some point this weekend, looks pretty simple though.

The only reason my unit tests weren't all breaking on SharpDX was because I never updated to the latest version.

**Comment by Warpten** [comment]
I'm currently trying to build SharpNav myself, having a tough time with Visual Studio not finding any dependency anymore now. Not sure what's up with that.

Thanks for the quick reply!

**Comment by Robmaister** [comment]
You should just be able to nuget restore the solution and all the dependencies should pull down properly. I've set up a SharpNav on a number of fresh machines.

CLI/GUI should only work with the Standalone configuration (since you're going to be exporting files anyways), Example should work in either Standalone or OpenTK, and Tests should work in all configurations.

If you get it working, please submit a pull request and I'll look it over.

**Comment by Robmaister** [comment]
Finally got around to updating packages, SharpDX is now properly supported with SharpDX.Mathematics.3.0.2
